- Formula/move2kube.rb
> Add move2kube homebrew formula

- Formula/move2kube.rb
> Change class name

- Formula/move2kube.rb
> Fix Bin Path

- Formula/move2kube.rb
> Fix Bin path with bottle cellar path

- .travis.yml
> Remove travis event type checks

- README.md
> Fix Readme with updated info

- .travis.yml
> Fix RVM and xquartz

- .travis.yml
> Remove brew doctor

- .travis.yml
> Fix formula location

- .travis.yml
> Use updated command for Homebrew install

- .travis.yml
> Add brew install git

- .travis.yml
> Add test bot command to script

- .travis.yml
> Simplify travis and use default test-bot

- Formula/move2kube.rb
> Fix go in Makefile

- .travis.yml
> Change to David's test-bot

- .travis.yml
- Formula/move2kube.rb
> Change test bot command

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/assignproject.yml
- .travis.yml
- Formula/move2kube.rb
- README.md
> chore: Change default branch to main

- .github/workflows/publish.yml
- .github/workflows/tests.yml
- Formula/move2kube.rb
> feat: add workflows to build the bottles

- Formula/move2kube.rb
> feat: add bottle for big sur

- Formula/move2kube.rb
> chore: update big_sur bottle

- Formula/move2kube.rb
> fix: apply automated fix because of deprecations

- Formula/move2kube.rb
> chore: update the stable formula to v0.3.0

- Formula/move2kube.rb
- Formula/move2kube@0.3.0-alpha.0.rb
- Formula/move2kube@0.3.0-alpha.1.rb
- Formula/move2kube@0.3.0-alpha.2.rb
- Formula/move2kube@0.3.0-alpha.3.rb
- Formula/move2kube@0.3.0-alpha.4.rb
- Formula/move2kube@0.3.0-beta.0.rb
- Formula/move2kube@0.3.0-beta.1.rb
- Formula/move2kube@0.3.0-beta.2.rb
- Formula/move2kube@0.3.0-beta.3.rb
- Formula/move2kube@0.3.0-rc.0.rb
- Formula/move2kube@0.3.0-rc.1.rb
- Formula/move2kube@0.3.0-rc.2.rb
- Formula/move2kube@0.3.0.rb
- Formula/move2kube@0.3.1-rc.0.rb
> fix: issue with asset url in stable formula

- Formula/move2kube.rb
> chore: update the stable formula with latest patch release info

- .github/workflows/publish.yml
> feat: add steps to update stable formula in publish workflow

- .github/workflows/publish.yml
> chore: fix syntax in workflow yaml

- .github/workflows/publish.yml
> chore: fix workflow syntax by putting the json array inside a yaml string

- .github/workflows/publish.yml
> chore: fix more syntax issues in publish workflow, also use the konveyor github action

- .github/workflows/publish.yml
> chore: fix workflow, extra quotes in filename causing the file to not be found

- .github/workflows/publish.yml
> chore: fix workflow, filepath of formula was incorrect
